// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDp36a01U08gdZLVHcDGy_C6gAg46wqmA',
    appId: '1:318002884140:web:790460d7c3473495f12b89',
    messagingSenderId: '318002884140',
    projectId: 'contractorhub-96017',
    authDomain: 'contractorhub-96017.firebaseapp.com',
    storageBucket: 'contractorhub-96017.firebasestorage.app',
    measurementId: 'G-D78WBD40QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlmDEBglspB-tGpI5_PX9A9S9kJQ31B8w',
    appId: '1:318002884140:android:33d29a49355896bff12b89',
    messagingSenderId: '318002884140',
    projectId: 'contractorhub-96017',
    storageBucket: 'contractorhub-96017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgIVSAQYPXd8e70RpvXoHbo8wePekcbH4',
    appId: '1:318002884140:ios:b28168abc41640e6f12b89',
    messagingSenderId: '318002884140',
    projectId: 'contractorhub-96017',
    storageBucket: 'contractorhub-96017.firebasestorage.app',
    iosBundleId: 'com.example.contractorHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgIVSAQYPXd8e70RpvXoHbo8wePekcbH4',
    appId: '1:318002884140:ios:b28168abc41640e6f12b89',
    messagingSenderId: '318002884140',
    projectId: 'contractorhub-96017',
    storageBucket: 'contractorhub-96017.firebasestorage.app',
    iosBundleId: 'com.example.contractorHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDp36a01U08gdZLVHcDGy_C6gAg46wqmA',
    appId: '1:318002884140:web:5a23e09a5ef3194df12b89',
    messagingSenderId: '318002884140',
    projectId: 'contractorhub-96017',
    authDomain: 'contractorhub-96017.firebaseapp.com',
    storageBucket: 'contractorhub-96017.firebasestorage.app',
    measurementId: 'G-8BBE1D3MEN',
  );
}
